name = "ez-manual-backend"
main = "backend/src/index.ts"
compatibility_date = "2024-10-04"
node_compat = true

[env.production]
name = "ez-manual-backend"
route = { pattern = "api.ez-manual.com", zone_name = "ez-manual.com" }

[[d1_databases]]
binding = "DB"
database_name = "ez-manual-db"
database_id = ""  # Fill after 'wrangler d1 create'

[[r2_buckets]]
binding = "STORAGE"
bucket_name = "ez-manual-storage"

[vars]
ENVIRONMENT = "production"
